jgaeddert/liquid-dsp

- makefile.in
```LDPATHS="-L/opt/local/lib" ./configure``` had no effect, this patch fixes this.
> Fix LDFLAGS in makefile.in to respect environment variables

- bootstrap.sh
- configure.ac
Instead of having to explicitly pass -I./scripts when running aclocal,
use the AC_CONFIG_MACRO_DIR() macro in configure.ac. This allows to
use "autoreconf" normally, without any hacks.
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
> configure.ac: use AC_CONFIG_MACRO_DIR

- src/framing/src/ofdmflexframegen.c
i don't think i quite understand why we need randomness at this point but in my testing, using the payload modem here sometimes caused strange results. i suspect that as we are in the header, we should use the header modem.
> use header modem to generate random header symbols

- include/liquid.h
- src/framing/src/flexframegen.c
- src/framing/src/ofdmflexframegen.c
it's common for code which takes user data for the incoming data to be
declared const very early on. in order to maintain const correctness, it
has to remain const through every call from there on.
> const correctness for framegen

- src/filter/src/iirfilt.c
The array allocators for IIR Filter create were using the wrong bounds.
> Fixed array allocators in IIR Filter creator.

- include/liquid.h
- src/framing/src/gmskframegen.c
* const correctness as with flexframegen/ofdmflexframegen
* _is_assembled
> nice-to-haves for gmskframegen

- makefile.in
Running `make install` should now also build the library. Currently
`make install` fails if the library wasn't built before - e.g. after
initial checkout.
Fixes #52.
> Enable build and install in one step

- configure.ac
gcc is fairly strict about this. just having -march doesn't necessarily
work, since the arch might be guaranteed to offer only a limited subset
of sse
there are usually two workarounds to this -- either set -march=native,
or explicitly set sse level with -msse. this does the latter.
> add -msse flag to makefile

- src/framing/src/flexframegen.c
- src/framing/src/flexframesync.c
This patch resolves undefined behavior in flexframegen.
In C, the evaluation order of any statement is not defined. The compiler may order the operations however it wants, although parens forces some ordering. Since msequence_advance(ms) is stateful, a different preamble is built depending on whether the compiler chooses to evaluate left-to-right or right-to-left.
I have gone with left-to-right, which I believe was the intended ordering. It seems this is the way clang chooses. gcc seemingly goes right-to-left. This means previously compiled versions may be incompatible with this patch, but moving forward all versions should be compatible with one another.
More broadly, we should thoroughly inspect for other instances of this sort bug. It seems just for msequence alone there are other …
> define order for msequence

- include/liquid.h
- src/filter/src/resamp.c
This function adjust the internal timing phase of the resampler, making it possible to
use custom timing error detectors with resamp.
> resamp: add adjust_timing_phase()

- src/framing/src/detector_cccf.c
nan (0/0) doesn't compare true, no matter which side of the < or > it is on. changing this test clamps the value correctly.
another question would be what causes tau_hat to be nan here. I'll try to dig in and figure out why that happens, but for now this at least prevents gmsk's assert from firing
> prevent nans from escaping detector

- makefile.in
The makefile.in used the variable LDFLAGS for both flags and libraries
to link. This will create problems as many flags need to appear before
the object files while the libraries to link need to appear after. A
similar problem stems from using CFLAGS for both include path
specifications and regular C compiler flags, as the CFLAGS are needed
for proper linking.
This patch splits LDFLAGS into LDFLAGS for flags only and LIBS for libs
only and splits CFLAGS into CFLAGS for compiler flags only and CPPFLAGS
for include path specifications only. Linking now changes LDFLAGS to
LIBS and adds CFLAGS and LDFLAGS at the beginning of the command. The
previously ignored @CPPFLAGS@ autoconf value is now also included in
CPPFLAGS.
> makefile.in: Fix overloading of LDFLAGS and CFLAGS

- examples/symtrack_cccf_example.c
- src/fft/src/spgram.c
- src/filter/src/iirfiltsos.c
reset() not clearing the window buffer turned out to be my bug, so I added a reset_all() function?
> spgram_reset(q) clears the internal spgram buffers (except for window buffer)

- examples/symtrack_cccf_example.c
Completes removal of spurious variables started in fb27bb8. Without this change, building with `make examples` fails.
> examples: remove cruft from symtrack_cccf example

- include/liquid.h
- include/liquid.internal.h
- src/framing/src/flexframegen.c
- src/framing/src/flexframesync.c
- src/framing/src/gmskframegen.c
- src/framing/src/gmskframesync.c
- src/framing/src/ofdmflexframegen.c
- src/framing/src/ofdmflexframesync.c
- src/framing/src/qpacketmodem.c
This PR builds on top of the user-defined header length PR from February
This allows user control of header mod/fec as well as soft demod for header and payload. This greatly improves the versatility of the flexframe object.
It'd be great to do gmsk like this too but after tinkering with it I must admit I can't figure out how to perform soft demod with gmsk.
> Header props

- examples/dsssframesync_example.c
- include/liquid.h
- include/liquid.internal.h
- makefile.in
- src/fec/src/packetizer.c
- src/framing/src/dsssframegen.c
- src/framing/src/dsssframesync.c
- src/framing/src/qdetector_cccf.c
- src/framing/src/qpacketmodem.c
- src/nco/src/nco.c
- src/nco/src/synth.c
- src/nco/src/synth_crcf.c
- tools/msequence_generator.c
This is what I've got so far for DSSS. This PR is probably 90% there for what might be mergeable. I think the big remaining missing pieces are debug printing and functions that can adjust the msequence polys. I didn't actually get around to implementing an early/late gate either, but I've convinced myself this probably doesn't matter for my uses.
Sadly this patch contains some unrelated formatting changes in qdetector. I could back these out pretty easily. I wasn't quite sure what the formatting guidelines were so I used clang-format with a config that seems to mostly match, but the result is that any file I touch might get its formatting re-arranged.
This is working better in my room tests than other modes, but there's still a lot I'm hoping to improve. One thing I'm curious about is how …
> DSSS generator/sync

- include/liquid.h
- src/framing/src/ofdmflexframesync.c
- src/multichannel/src/ofdmframesync.c
This patch implements counter parts of ofdmflexframesync_get_cfo()/ofdmframesync_get_cfo(). This was useful for me to hide liquid-dsp internals from one of open source 3rd parties which tried to dig directly into liquid-dsp internals. Perhaps it could be useful for other people.
> Implement ofdmflexframesync_set_cfo()/ofdmframesync_set_cfo()

- src/math/src/poly.lagrange.c
- src/math/tests/polynomial_autotest.c
Highlighted by issue #165, roots with wrong sign (-) were fed to lagrange polynomial co-efficients calculations. Also added a couple of unit-tests to catch the regression.
Signed-off-by: Faheem Sheikh <fahim.sheikh@gmail.com>
> math: Fix bug in lagrange polynomial

- include/liquid.h
- include/liquid.internal.h
Summary: IIRFILT second order section API is missing from external liquid header.
Fixes #204
> iirfilt: Add missing SOS API for iirfilt object

- examples/gmskframesync_example.c
- include/liquid.h
- src/framing/bench/gmskframesync_benchmark.c
- src/framing/src/gmskframegen.c
- src/framing/src/gmskframesync.c
EDIT: I also added the ```k``` and ```m``` parameters so that ```gmskframegen_create``` has the same parameters as ```gmskmod_create```.
> gmskframe: allow specifying BT parameter

- src/equalization/tests/eqlms_cccf_autotest.c
- src/fec/src/fec_hamming3126.c
- src/filter/src/dds.c
- src/framing/src/bpresync.c
- src/framing/src/framegen64.c
- src/math/src/poly.lagrange.c
- src/multichannel/src/ofdmframesync.c
- src/nco/src/nco.c
- src/optim/src/gradsearch.c
- src/sequence/src/bsequence.c
- src/utility/src/byte_utilities.c
This patch fixes errors when liquid is build with `-fsanitize=address,undefined`
Fixes #244
> Fix clang sanitizer errors

- include/liquid.internal.h
- src/fec/src/fec_conv.c
libfec uses "negative" polynomials to represent an inverted symbol output from the convolutional encoder, and sets the Viterbi decoder up accordingly. This patch adds support for that feature in the encoder implemented in liquid-dsp.
Even though libfec only supports one polynomial for all instances of Viterbi decoders, this should allow users to switch the [hardcoded polynomials](https://github.com/jgaeddert/liquid-dsp/blob/master/src/fec/src/fec_conv_poly.c) to include inverted symbols (i.e. CCSDS and NASA-DSN specification of K=7 encoder).
> Support encoding with inverted polynomials

- src/framing/src/dsssframesync.c
This is the fix for the ```dsssframesync_execute``` function in version 1.4.0 described in issue #114.
> dsssframesync: fix premature return from dsss_framesync_execute

- src/framing/src/dsssframesync.c
There's no need to call a function to call another function once per sample. This reverts The functionality to how it was before https://github.com/jgaeddert/liquid-dsp/pull/281/files broke it
> use original dsssframesync code

- src/filter/src/cheby2.c
The number of analog zeros that this function outputs is 2*L; fix the documentation to match that.
> iirdes: fix number of zeroes in the docs

- makefile.in
When DESTDIR is used, the target of the symlinks is incorrect -- but the symlinks are pointing to a file in the same directory, so there's no need to include the directory at all.
> build: don't include directories in symlink targets

- bench/fftbench.c
- examples/fft_example.c
- include/liquid.h
- include/liquid.internal.h
- sandbox/fskcorr_test.c
- src/fft/bench/fft_runbench.c
- src/fft/src/fft_common.proto.c
- src/fft/src/fft_mixed_radix.proto.c
- src/fft/src/fft_rader.proto.c
- src/fft/src/fft_rader2.proto.c
- src/fft/src/spgram.proto.c
- src/filter/src/fftfilt.proto.c
- src/filter/src/firdespm_halfband.c
- src/framing/src/qdetector_cccf.c
- src/framing/src/qpilotsync.c
- src/modem/src/fskdem.c
- src/multichannel/src/firpfbch.proto.c
- src/multichannel/src/firpfbch2.proto.c
- src/multichannel/src/firpfbchr.proto.c
- src/multichannel/src/ofdmframegen.c
- src/multichannel/src/ofdmframesync.c
* add fft_malloc/fft_free wrapper methods to API
* add FFT_MALLOC/FFT_FREE macros to internal API that use FFTW's fftwf_malloc/fftwf_free aligned memory methods if HAVE_FFTW3_H and not using --enable-fftoverrride
* use new macros inside objects that use FFTs internally
> fft: add fft_malloc/fft_free API for FFTW aligned memory

- configure.ac
- src/dotprod/src/dotprod_rrrf.sse4.c
Fix what I think was causing said errors (imm8 is supposed to be 8-bits, not 32-bits)
This reverts commit c99e7d878e16901a9f376b317ddb3b3bb75c8ed0.
> Fix what I think was causing errors with the SSE4.1 dotprod

- makefile.in
A SONAME was introduced to libliquid and used in installation file names however the shared library was always compiled with 'libliquid.so' as the SONAME rather than 'libliquid.so.1' as was probably intended.
Fix that and introduce a SOVERSION variable to the makefile so that it is defined in a single place only.
> Fix SONAME not set in shared library

- src/filter/src/bessel.c
Fixes out-of-bounds array write described in #235
This patch is also applied in the Debian package since version 1.5.0-2.
> bessel: fix array out of bounds write in bessel_azpkf()
